################################################################################
# Cloud formation definition for dpnt_coverage
################################################################################
AWSTemplateFormatVersion: '2010-09-09'
Description: >
    Cloudfront template to run TesterCluster using ECS
Parameters:
    EcsClusterName:
        Type: String
        Description: >
            associated
            Specifies the ECS Cluster Name with which the resources would be
        Default: 'TesterCluster'
Resources:
    MyCluster:
        Type: "AWS::ECS::Cluster"
        Properties:
            ClusterName: !Ref EcsClusterName
