################################################################################
# Docker definition.
################################################################################
FROM ubuntu:16.04

# Installing dependencies
# TODO: Install code coverage dependencies
RUN apt-get update -y \
    && apt-get -y install \
    --no-install-recommends \
        python=2.7.11-1 \
        python-pip=8.1.1-2ubuntu0.4
