S3_ENDPOINT: "http://127.0.0.1:9000"
S3_REGION: "us-east-1"

ECS_ENDPOINT: "http://127.0.0.1:9988"
ECS_REGION: "local"
ECS_TASK_CLUSTER: "local-test-cluster"
ECS_TASK_DEFINITION_PREFIX: "accelerate-io/dpnt-coverage-"
ECS_TASK_LAUNCH_TYPE: "FARGATE"
ECS_VPC_SUBNET: "local-subnet-x"
ECS_VPC_SECURITY_GROUP: "sg-local-security"
ECS_VPC_ASSIGN_PUBLIC_IP: "DISABLED"

SQS_ENDPOINT: "http://127.0.0.1:9324"
SQS_REGION: "elasticmq"
SQS_QUEUE_URL: "http://127.0.0.1:9324/queue/participant-events"